puts 'ruby' == 'ruby'
puts 'ruby' == 'Ruby'
puts 'ruby' != 'peri'
puts 'ruby' != 'ruby'
puts "\n"
puts 'a' < 'b'
puts 'a' < 'A'
puts 'a' > 'A'
puts 'abc' < 'def'
puts 'abc' < 'ab'
puts 'abc' < 'abcd'
puts 'あいうえお' < 'かきくけこ'